// Generated by scripts/build_data.py — do not edit by hand.
window.SH_FOOD = {
  "districts": [
    {
      "id": "huangpu",
      "name": "黄浦区",
      "en": "Huangpu",
      "theme": "老城厢 · 海派本帮",
      "styleNote": "Art Deco 石库门风",
      "blurb": "上海的城市原点。外滩、豫园与老城厢之间，藏着大壶春、鲜得来这些非遗级老字号，本帮菜的浓油赤酱从这里走向全城。",
      "x": 58,
      "y": 40,
      "dishes": [
        {
          "id": "huangpu-dahu-shengjian",
          "name": "大壶春生煎",
          "type": "面点",
          "taste": "咸鲜焦香",
          "tasteGroup": "咸鲜",
          "tags": [
            "咸鲜",
            "面点",
            "非遗"
          ],
          "rating": 4.8,
          "detail": "创建于 1932 年的老字号，上海生煎“清水派”代表：半发酵面皮、肉馅不加皮冻，煎出厚而焦脆的底板，肉香与麦香交融。制作技艺 2019 年入选黄浦区非物质文化遗产。",
          "img": "images/huangpu-dahu-shengjian.jpg",
          "credit": {
            "title": "File:Shengjian Mantou on a Pan.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Shengjian_Mantou_on_a_Pan.jpg",
            "license": "CC BY-SA 2.0"
          }
        },
        {
          "id": "huangpu-paigu-niangao",
          "name": "鲜得来排骨年糕",
          "type": "小吃",
          "taste": "甜咸酱香",
          "tasteGroup": "浓油赤酱",
          "tags": [
            "甜咸",
            "小吃",
            "非遗"
          ],
          "rating": 4.7,
          "detail": "始创于 1921 年的“排骨年糕大王”：猪排拍松上浆后炸至金黄酥脆，配宁波水磨年糕，淋甜面酱与辣酱油，咸甜交织，是几代上海人的市井记忆，技艺同样入选黄浦区非遗。",
          "img": "images/huangpu-paigu-niangao.jpg",
          "credit": {
            "title": "File:Xiandelai Pork chop with Nian gao-20240106.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Xiandelai_Pork_chop_with_Nian_gao-20240106.jpg",
            "license": "CC BY-SA 4.0"
          }
        },
        {
          "id": "huangpu-yuyuan-xiaolong",
          "name": "豫园南翔小笼",
          "type": "面点",
          "taste": "咸鲜多汁",
          "tasteGroup": "咸鲜",
          "tags": [
            "咸鲜",
            "面点",
            "招牌"
          ],
          "rating": 4.8,
          "detail": "源自嘉定南翔，却在豫园“南翔馒头店”发扬为上海点心的金字招牌：皮薄如纸、馅足汁多，“轻轻提，慢慢移，先开窗，后喝汤”。与嘉定、虹口一脉相承。",
          "img": "images/huangpu-yuyuan-xiaolong.jpg",
          "credit": {
            "title": "File:Xiao Long Bao by Junhao!.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Xiao_Long_Bao_by_Junhao!.jpg",
            "license": "CC BY 2.0"
          }
        }
      ]
    },
    {
      "id": "jingan",
      "name": "静安区",
      "en": "Jing'an",
      "theme": "摩登轻奢 · 西点记忆",
      "styleNote": "奶油白 × 香槟金现代风",
      "blurb": "南京西路与愚园路交汇的精致生活区，张爱玲与《繁花》都绕不开的西点香气从这里飘出，是海派洋气的另一种打开方式。",
      "x": 48,
      "y": 28,
      "dishes": [
        {
          "id": "jingan-lizi-dangao",
          "name": "凯司令栗子蛋糕",
          "type": "甜品",
          "taste": "香甜绵密",
          "tasteGroup": "甜糯",
          "tags": [
            "香甜",
            "甜品",
            "老字号"
          ],
          "rating": 4.6,
          "detail": "1928 年诞生的中国第一家国货西餐馆，张爱玲笔下的“栗子蛋糕”、《繁花》里爷叔的心头好。当季栗子打成的栗蓉铺满蛋糕，白脱奶油绵密香滑。",
          "img": "images/jingan-lizi-dangao.jpg",
          "credit": {
            "title": "File:Making mont Blanc cup cake.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Making_mont_Blanc_cup_cake.jpg",
            "license": "CC BY-SA 4.0"
          }
        },
        {
          "id": "jingan-shuijing-xiaren",
          "name": "静安宾馆水晶虾仁",
          "type": "菜肴",
          "taste": "咸鲜清爽",
          "tasteGroup": "清鲜",
          "tags": [
            "咸鲜",
            "本帮",
            "名菜"
          ],
          "rating": 4.7,
          "detail": "静安宾馆看家名菜，曾被评为“上海第一名菜”。河虾仁上浆滑油，成菜晶莹剔透、粒粒弹嫩，仅以薄芡与少许盐吊出虾的本味。",
          "img": "images/jingan-shuijing-xiaren.jpg",
          "credit": {
            "title": "File:Shrimp Stir-fried with Dragon Well Tea.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Shrimp_Stir-fried_with_Dragon_Well_Tea.jpg",
            "license": "CC BY-SA 4.0"
          }
        }
      ]
    },
    {
      "id": "xuhui",
      "name": "徐汇区",
      "en": "Xuhui",
      "theme": "梧桐法式 · 中西合璧",
      "styleNote": "米白 × 勃艮第红法式风",
      "blurb": "衡山路梧桐树影下的法式街区，既有“点心大王”乔家栅的本土传承，也有龙华寺千年素斋的禅意，中西风味在这里握手。",
      "x": 50,
      "y": 40,
      "dishes": [
        {
          "id": "xuhui-leishayuan",
          "name": "乔家栅擂沙圆",
          "type": "点心",
          "taste": "甜糯沙香",
          "tasteGroup": "甜糯",
          "tags": [
            "甜糯",
            "点心",
            "非遗"
          ],
          "rating": 4.7,
          "detail": "“点心大王”乔家栅的镇店名点：糯米汤团煮熟沥干，滚上崇明大红袍赤豆炒磨的紫红豆沙粉，冷热皆宜、便于携带，是上海市级非遗糕点技艺的代表。",
          "img": "images/xuhui-leishayuan.jpg",
          "credit": {
            "title": "File:Funwari Meijin Kinako Mochi 01.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Funwari_Meijin_Kinako_Mochi_01.jpg",
            "license": "Public domain"
          }
        },
        {
          "id": "xuhui-longhua-sumian",
          "name": "龙华素斋面",
          "type": "面点",
          "taste": "清鲜素雅",
          "tasteGroup": "清鲜",
          "tags": [
            "清鲜",
            "素斋",
            "面点"
          ],
          "rating": 4.6,
          "detail": "龙华寺素斋传承千年佛门素食传统，一碗素面浇头丰盛，素鸭、香菇、面筋卤香入味，汤头清鲜，素斋制作技艺亦是徐汇的非物质文化遗产。",
          "img": "images/xuhui-longhua-sumian.jpg",
          "credit": {
            "title": "File:Vietnamese vegetarian crab noodle soup.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Vietnamese_vegetarian_crab_noodle_soup.jpg",
            "license": "CC0"
          }
        }
      ]
    },
    {
      "id": "changning",
      "name": "长宁区",
      "en": "Changning",
      "theme": "虹桥烟火 · 社区食堂",
      "styleNote": "暖橙街头手写风",
      "blurb": "虹桥开发区与老新村并存的城区，仙霞路、天山路的烟火气里，藏着一批做了几十年的社区老店，实惠又扎实。",
      "x": 42,
      "y": 38,
      "dishes": [
        {
          "id": "changning-huade-dabao",
          "name": "华德大包",
          "type": "面点",
          "taste": "咸鲜葱香",
          "tasteGroup": "咸鲜",
          "tags": [
            "咸鲜",
            "面点",
            "老字号"
          ],
          "rating": 4.5,
          "detail": "长宁老字号华德饭店的招牌，以“个大、皮薄、馅多、实惠”闻名，还曾被新华社“千城早餐”点名，是长宁人早餐桌上的烟火气。",
          "img": "images/changning-huade-dabao.jpg",
          "credit": {
            "title": "File:Nangua Baozi (chinese dumplings).jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Nangua_Baozi_(chinese_dumplings).jpg",
            "license": "CC BY 2.0"
          }
        },
        {
          "id": "changning-jinfen-youxia",
          "name": "金芬食府油爆虾",
          "type": "菜肴",
          "taste": "咸甜浓郁",
          "tasteGroup": "浓油赤酱",
          "tags": [
            "浓油赤酱",
            "本帮",
            "海鲜"
          ],
          "rating": 4.6,
          "detail": "扎根长宁几十年的本帮馆子，招牌油爆虾壳酥肉弹，裹着浓油赤酱的甜咸汁，与毛蟹炒年糕、响油鳝丝并称本帮老三样。",
          "img": "images/changning-jinfen-youxia.jpg",
          "credit": {
            "title": "File:Xiaren Du Mianjin 虾仁独面筋 (Braised Fried Gluten with Shrimp).jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Xiaren_Du_Mianjin_%E8%99%BE%E4%BB%81%E7%8B%AC%E9%9D%A2%E7%AD%8B_(Braised_Fried_Gluten_with_Shrimp).jpg",
            "license": "CC BY-SA 4.0"
          }
        }
      ]
    },
    {
      "id": "hongkou",
      "name": "虹口区",
      "en": "Hongkou",
      "theme": "弄堂铅字 · 市井烟火",
      "styleNote": "老报纸铅字印刷风",
      "blurb": "山阴路、提篮桥的老弄堂里，鲁迅住过，小笼和糕团也养大了几代虹口人，市井气息像铅字一样清晰扎实。",
      "x": 58,
      "y": 30,
      "dishes": [
        {
          "id": "hongkou-wanshouzhai-xiaolong",
          "name": "万寿斋小笼包",
          "type": "面点",
          "taste": "咸鲜带甜",
          "tasteGroup": "咸鲜",
          "tags": [
            "咸鲜",
            "面点",
            "排队王"
          ],
          "rating": 4.7,
          "detail": "山阴路上开了约 70 年的“虹口排队王”，小笼属南翔一脉，皮薄馅大、汤汁鲜甜不腻，配一碟香醋，是虹口小囡从小吃到大的味道。",
          "img": "images/hongkou-wanshouzhai-xiaolong.jpg",
          "credit": {
            "title": "File:2019-02-22 Xiaolongbao in \"Taste Of Shanghai\" restaurant, Sydney, Australia.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:2019-02-22_Xiaolongbao_in_%22Taste_Of_Shanghai%22_restaurant,_Sydney,_Australia.jpg",
            "license": "CC BY-SA 4.0"
          }
        },
        {
          "id": "hongkou-niangaotuan",
          "name": "虹口年糕团",
          "type": "小吃",
          "taste": "软糯咸甜",
          "tasteGroup": "甜糯",
          "tags": [
            "甜糯",
            "小吃",
            "糕团"
          ],
          "rating": 4.6,
          "detail": "虹口糕团厂的招牌，糯米团现揉现包：咸口夹油条、榨菜、肉松，甜口夹芝麻白糖，咬一口软糯拉丝，是老上海糕团文化的活化石。",
          "img": "images/hongkou-niangaotuan.jpg",
          "credit": {
            "title": "File:Chinese rice cake 3.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Chinese_rice_cake_3.jpg",
            "license": "CC0"
          }
        }
      ]
    },
    {
      "id": "yangpu",
      "name": "杨浦区",
      "en": "Yangpu",
      "theme": "学府青春 · 老店坚守",
      "styleNote": "亮黄 × 深蓝学院贴纸风",
      "blurb": "大学路与平凉路并存，一边是年轻人的潮流，一边是 1958 年就开张的清真老店，一口牛肉煎包吃出两代人的坚守。",
      "x": 62,
      "y": 20,
      "dishes": [
        {
          "id": "yangpu-yixinzhai-niuroujianbao",
          "name": "一心斋牛肉煎包",
          "type": "面点",
          "taste": "鲜香多汁",
          "tasteGroup": "咸鲜",
          "tags": [
            "咸鲜",
            "面点",
            "非遗"
          ],
          "rating": 4.7,
          "detail": "平凉路上始于 1958 年的清真老店，“清真菜点制作技艺”是上海市级非遗。一两二面皮配一两四牛肉馅，平底锅煎出金脆外壳，一锅 50 只仍供不应求。",
          "img": "images/yangpu-yixinzhai-niuroujianbao.jpg",
          "credit": {
            "title": "File:牛肉锅贴 Pan-fried Beef Dumplings - Ants Bistro.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:%E7%89%9B%E8%82%89%E9%94%85%E8%B4%B4_Pan-fried_Beef_Dumplings_-_Ants_Bistro.jpg",
            "license": "CC BY-SA 2.0"
          }
        }
      ]
    },
    {
      "id": "putuo",
      "name": "普陀区",
      "en": "Putuo",
      "theme": "古寺禅意 · 百年羊汤",
      "styleNote": "石青 × 灰蓝禅意风",
      "blurb": "真如寺、玉佛寺的梵音与真如老街的羊肉香交织，普陀的味道带着寺庙的素净与市集的温热。",
      "x": 34,
      "y": 28,
      "dishes": [
        {
          "id": "putuo-zhenru-yangrou",
          "name": "真如羊肉",
          "type": "菜肴",
          "taste": "咸甜鲜糯",
          "tasteGroup": "浓油赤酱",
          "tags": [
            "浓油赤酱",
            "羊肉",
            "非遗"
          ],
          "rating": 4.6,
          "detail": "成名于清乾隆年间的百年老字号：红烧羊肉以老汤加黄酒焖煮，卤浓肥甜；白切羊肉原汁原味、酥而不烂，2007 年入选上海市非遗。",
          "img": "images/putuo-zhenru-yangrou.jpg",
          "credit": {
            "title": "File:Braised Lamb Neck – Scallion Pancakes, Pickled Vegetables.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Braised_Lamb_Neck_%E2%80%93_Scallion_Pancakes,_Pickled_Vegetables.jpg",
            "license": "CC BY 2.0"
          }
        },
        {
          "id": "putuo-yufo-suzhai",
          "name": "玉佛寺素斋",
          "type": "菜肴",
          "taste": "清鲜醇香",
          "tasteGroup": "清鲜",
          "tags": [
            "清鲜",
            "素斋",
            "禅意"
          ],
          "rating": 4.6,
          "detail": "安远路玉佛寺的素斋远近闻名，素鸭豆香浓郁、几可乱真，素面清鲜暖胃，不少香客专程为这一口而来，承载着海派佛教饮食文化。",
          "img": "images/putuo-yufo-suzhai.jpg",
          "credit": {
            "title": "File:A Five selections of Chinese Vegetarian Platter in Hong Kong.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:A_Five_selections_of_Chinese_Vegetarian_Platter_in_Hong_Kong.jpg",
            "license": "CC BY-SA 4.0"
          }
        }
      ]
    },
    {
      "id": "minhang",
      "name": "闵行区",
      "en": "Minhang",
      "theme": "七宝老街 · 古镇市集",
      "styleNote": "灯笼红 × 木牌坊集市风",
      "blurb": "始于北宋的七宝老街，一千年里只做一件事：用方糕、汤圆和羊肉留住过路人的胃。",
      "x": 45,
      "y": 52,
      "dishes": [
        {
          "id": "minhang-qibao-fanggao",
          "name": "七宝方糕",
          "type": "点心",
          "taste": "甜糯清香",
          "tasteGroup": "甜糯",
          "tags": [
            "甜糯",
            "点心",
            "非遗"
          ],
          "rating": 4.6,
          "detail": "七宝老街一品方糕店的招牌，闵行区非物质文化遗产。糯米粉蒸制、内嵌豆沙或黑洋酥，口感软糯不粘牙，寓意“年年高升”。",
          "img": "images/minhang-qibao-fanggao.jpg",
          "credit": {
            "title": "File:Cake Cafe Red Beans & Rice Partly Eaten.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Cake_Cafe_Red_Beans_%26_Rice_Partly_Eaten.jpg",
            "license": "CC BY 2.0"
          }
        },
        {
          "id": "minhang-qibao-tangyuan",
          "name": "七宝汤圆",
          "type": "小吃",
          "taste": "咸甜皆宜",
          "tasteGroup": "甜糯",
          "tags": [
            "甜糯",
            "小吃",
            "水乡"
          ],
          "rating": 4.7,
          "detail": "始于北宋的老街汤圆店现包现煮，皮薄馅大，鲜肉、黑洋酥、荠菜三种馅各有拥趸，大颗汤圆两三个就管饱。",
          "img": "images/minhang-qibao-tangyuan.jpg",
          "credit": {
            "title": "File:Glutinous Rive Balls (Tang Yuan).jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Glutinous_Rive_Balls_(Tang_Yuan).jpg",
            "license": "CC BY-SA 4.0"
          }
        }
      ]
    },
    {
      "id": "baoshan",
      "name": "宝山区",
      "en": "Baoshan",
      "theme": "吴淞江鲜 · 钢铁滨江",
      "styleNote": "钢板铆钉 × 江蓝工业风",
      "blurb": "吴淞口的江风里，鮰鱼从江里游上餐桌；罗店的手工鱼圆则把水乡的手艺揉进了每一口弹嫩里。",
      "x": 30,
      "y": 18,
      "dishes": [
        {
          "id": "baoshan-hongshaohuiyu",
          "name": "红烧鮰鱼",
          "type": "菜肴",
          "taste": "咸甜浓郁",
          "tasteGroup": "浓油赤酱",
          "tags": [
            "浓油赤酱",
            "江鲜",
            "非遗"
          ],
          "rating": 4.7,
          "detail": "吴淞口的经典江鲜，鮰鱼胶质丰厚，以本帮“浓油赤酱”技法烧至色泽亮红、酱汁粘唇，入口咸中带甜、鱼肉细嫩，是宝山非遗美食。",
          "img": "images/baoshan-hongshaohuiyu.jpg",
          "credit": {
            "title": "File:202403 Braised Rice-Fish from Qingtian.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:202403_Braised_Rice-Fish_from_Qingtian.jpg",
            "license": "CC BY-SA 4.0"
          }
        },
        {
          "id": "baoshan-luodian-yuyuan",
          "name": "罗店鱼圆",
          "type": "小吃",
          "taste": "清鲜弹嫩",
          "tasteGroup": "清鲜",
          "tags": [
            "清鲜",
            "鱼鲜",
            "非遗"
          ],
          "rating": 4.5,
          "detail": "宝山区非物质文化遗产。鲜活鱼肉去骨剁泥、沿同一方向持续搅打，从虎口挤出，在 40℃ 微沸水中养熟，莹润如玉、弹嫩爽滑，是节庆餐桌的团圆味。",
          "img": "images/baoshan-luodian-yuyuan.jpg",
          "credit": {
            "title": "File:Fish Ball Hor Fun Rice Noodle Soup Salt-Baked Chicken Rice - Hakka Teahouse, Glen Waverley AUD9 lunch special.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Fish_Ball_Hor_Fun_Rice_Noodle_Soup_Salt-Baked_Chicken_Rice_-_Hakka_Teahouse,_Glen_Waverley_AUD9_lunch_special.jpg",
            "license": "CC BY-SA 2.0"
          }
        }
      ]
    },
    {
      "id": "jiading",
      "name": "嘉定区",
      "en": "Jiading",
      "theme": "江南古镇 · 小笼之源",
      "styleNote": "宣纸 × 墨笔水墨风",
      "blurb": "南翔古镇的小笼，是上海小吃走向全国的原点；一只 18 褶的包子，藏着 150 年的江南手艺。",
      "x": 16,
      "y": 15,
      "dishes": [
        {
          "id": "jiading-nanxiang-xiaolong",
          "name": "南翔小笼包",
          "type": "面点",
          "taste": "咸鲜多汁",
          "tasteGroup": "咸鲜",
          "tags": [
            "咸鲜",
            "面点",
            "国家级非遗"
          ],
          "rating": 4.9,
          "detail": "始创于清同治十年（1871 年），国家级非物质文化遗产。不发酵精面粉做皮，每只面皮仅 1.5 毫米厚、重 8 克，包入 16 克馅料、捏出 18 个以上折褶，蒸熟后晶莹剔透，一咬一包汤。",
          "img": "images/jiading-nanxiang-xiaolong.jpg",
          "credit": {
            "title": "File:Xiaolongbao Shanghai.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Xiaolongbao_Shanghai.jpg",
            "license": "CC BY-SA 4.0"
          }
        }
      ]
    },
    {
      "id": "pudong",
      "name": "浦东新区",
      "en": "Pudong",
      "theme": "摩天霓虹 · 乡愁本帮",
      "styleNote": "深蓝夜空 × 霓虹玻璃风",
      "blurb": "陆家嘴的天际线之下，高桥的松饼与三林的老八样仍在提醒人们：再摩登的浦东，也留着灶台上的乡愁。",
      "x": 70,
      "y": 42,
      "dishes": [
        {
          "id": "pudong-gaoqiao-songbing",
          "name": "高桥松饼",
          "type": "点心",
          "taste": "甜酥绵软",
          "tasteGroup": "甜糯",
          "tags": [
            "甜糯",
            "点心",
            "沪郊百宝"
          ],
          "rating": 4.6,
          "detail": "“沪郊百宝”之一，高桥人传承百年的本帮糕饼：外皮层层酥松，内馅有豆沙、核桃、红枣等口味，蓬松甜软，是老浦东茶桌上的点心记忆。",
          "img": "images/pudong-gaoqiao-songbing.jpg",
          "credit": {
            "title": "File:Sweet potato flaky pastry.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Sweet_potato_flaky_pastry.jpg",
            "license": "CC BY-SA 3.0"
          }
        },
        {
          "id": "pudong-sanlin-kousansi",
          "name": "三林扣三丝",
          "type": "菜肴",
          "taste": "咸鲜清润",
          "tasteGroup": "咸鲜",
          "tags": [
            "咸鲜",
            "本帮",
            "宴席"
          ],
          "rating": 4.7,
          "detail": "三林本帮菜“老八样”中的主角：鸡丝、火腿丝、笋丝三色相间，入盅压实后反扣装盘、浇上清汤，刀工与火候尽显本帮宴席功夫。",
          "img": "images/pudong-sanlin-kousansi.JPG",
          "credit": {
            "title": "File:Braised Shredded Chicken with Ham and Dried Tofu 2011-04.JPG",
            "url": "https://commons.wikimedia.org/wiki/File:Braised_Shredded_Chicken_with_Ham_and_Dried_Tofu_2011-04.JPG",
            "license": "CC BY-SA 3.0"
          }
        }
      ]
    },
    {
      "id": "jinshan",
      "name": "金山区",
      "en": "Jinshan",
      "theme": "枫泾桥乡 · 水乡四宝",
      "styleNote": "青石板 × 水绿拱桥风",
      "blurb": "枫泾古镇的桥头，丁蹄的酱香与状元糕的桂花香飘了快两百年，“枫泾四宝”是水乡人家的体面。",
      "x": 26,
      "y": 68,
      "dishes": [
        {
          "id": "jinshan-fengjing-dingti",
          "name": "枫泾丁蹄",
          "type": "菜肴",
          "taste": "咸甜酱香",
          "tasteGroup": "浓油赤酱",
          "tags": [
            "浓油赤酱",
            "蹄髈",
            "老字号"
          ],
          "rating": 4.8,
          "detail": "清咸丰二年（1852 年）丁义兴酒店的招牌，以太湖良种枫泾猪前蹄为料，经“八道工艺”与百年老汤烧制，酱红透亮、酥烂入味、肥而不腻，是枫泾四宝之首。",
          "img": "images/jinshan-fengjing-dingti.jpg",
          "credit": {
            "title": "File:Braised pig trotters.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Braised_pig_trotters.jpg",
            "license": "CC BY 2.0"
          }
        },
        {
          "id": "jinshan-fengjing-zhuangyuangao",
          "name": "枫泾状元糕",
          "type": "点心",
          "taste": "清甜软糯",
          "tasteGroup": "甜糯",
          "tags": [
            "甜糯",
            "点心",
            "四宝"
          ],
          "rating": 4.5,
          "detail": "因乾隆年间枫泾状元蔡以台而得名，寓意金榜题名。糯米粉加桂花糖蒸制，清甜软糯、香气悠长，与丁蹄、天香豆腐干、金枫黄酒并称“枫泾四宝”。",
          "img": "images/jinshan-fengjing-zhuangyuangao.jpg",
          "credit": {
            "title": "File:HK Sheung Wan 金鑽海鮮皇宮酒家 Daimond Restaurant 甜品 Dessert 桂花榚 Osmanthus Jelly cake Mar-2012.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:HK_Sheung_Wan_%E9%87%91%E9%91%BD%E6%B5%B7%E9%AE%AE%E7%9A%87%E5%AE%AE%E9%85%92%E5%AE%B6_Daimond_Restaurant_%E7%94%9C%E5%93%81_Dessert_%E6%A1%82%E8%8A%B1%E6%A6%9A_Osmanthus_Jelly_cake_Mar-2012.jpg",
            "license": "CC BY-SA 3.0"
          }
        }
      ]
    },
    {
      "id": "songjiang",
      "name": "松江区",
      "en": "Songjiang",
      "theme": "云间古邑 · 鱼米之乡",
      "styleNote": "书卷米白 × 黛青云纹风",
      "blurb": "“先有松江府，后有上海滩”。叶榭的软糕、张泽的羊肉，都是这片鱼米之乡四百年来递给上海的伴手礼。",
      "x": 30,
      "y": 55,
      "dishes": [
        {
          "id": "songjiang-yexie-ruangao",
          "name": "叶榭软糕",
          "type": "点心",
          "taste": "松软香甜",
          "tasteGroup": "甜糯",
          "tags": [
            "甜糯",
            "点心",
            "非遗"
          ],
          "rating": 4.6,
          "detail": "始产于明代、已有 400 多年历史的上海市非遗。以优质粳米蒸制，松、软、香、甜、肥，糕面可印“花好月圆”等吉语，是松江人的伴手礼。",
          "img": "images/songjiang-yexie-ruangao.jpg",
          "credit": {
            "title": "File:Fa gao 笑口发糕 Steamed rice-cakes.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Fa_gao_%E7%AC%91%E5%8F%A3%E5%8F%91%E7%B3%95_Steamed_rice-cakes.jpg",
            "license": "CC BY-SA 2.0"
          }
        },
        {
          "id": "songjiang-zhangze-yangrou",
          "name": "张泽羊肉",
          "type": "菜肴",
          "taste": "鲜香醇厚",
          "tasteGroup": "咸鲜",
          "tags": [
            "鲜香",
            "羊肉",
            "伏羊"
          ],
          "rating": 4.6,
          "detail": "松江张泽的伏羊传统：白切羊肉皮嫩肉酥，配一碗羊杂汤与一碟蘸料，讲究原汁原味，每年伏天“吃羊肉、喝烧酒”的习俗延续百年。",
          "img": "images/songjiang-zhangze-yangrou.jpg",
          "credit": {
            "title": "File:Instant-boiled mutton with sesame sauce.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Instant-boiled_mutton_with_sesame_sauce.jpg",
            "license": "CC BY-SA 4.0"
          }
        }
      ]
    },
    {
      "id": "qingpu",
      "name": "青浦区",
      "en": "Qingpu",
      "theme": "淀湖水乡 · 舟楫之味",
      "styleNote": "水蓝 × 竹青波纹风",
      "blurb": "朱家角的水巷里，阿婆粽和扎肉的香气顺着炊烟飘过石桥；淀山湖的风一吹，就是最江南的上海。",
      "x": 22,
      "y": 42,
      "dishes": [
        {
          "id": "qingpu-zhujiajiao-zharou",
          "name": "朱家角扎肉",
          "type": "菜肴",
          "taste": "咸甜酥糯",
          "tasteGroup": "浓油赤酱",
          "tags": [
            "浓油赤酱",
            "水乡",
            "招牌"
          ],
          "rating": 4.6,
          "detail": "朱家角古镇的招牌：五花肉用粽叶裹起、稻草扎紧，入老卤焖煮，肉酥酱香中带着粽叶清香，一只只码在锅边，是最地道的水乡下酒菜。",
          "img": "images/qingpu-zhujiajiao-zharou.jpg",
          "credit": {
            "title": "File:Red braised pork belly 红烧肉 hóngshāoròu 23 January 2025 Filipinas4.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Red_braised_pork_belly_%E7%BA%A2%E7%83%A7%E8%82%89_h%C3%B3ngsh%C4%81or%C3%B2u_23_January_2025_Filipinas4.jpg",
            "license": "CC BY-SA 4.0"
          }
        },
        {
          "id": "qingpu-ajiaozong",
          "name": "朱家角阿婆粽",
          "type": "小吃",
          "taste": "咸鲜油润",
          "tasteGroup": "咸鲜",
          "tags": [
            "咸鲜",
            "小吃",
            "水乡"
          ],
          "rating": 4.7,
          "detail": "古镇阿婆们现包现煮，糯米油润、蛋黄流油、肉块酥烂，名气不输五芳斋；与扎肉、大闸蟹、肉馅烧卖共同构成朱家角的小吃图景。",
          "img": "images/qingpu-ajiaozong.jpg",
          "credit": {
            "title": "File:Kyoto zongzi japonais.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Kyoto_zongzi_japonais.jpg",
            "license": "CC BY-SA 4.0"
          }
        }
      ]
    },
    {
      "id": "fengxian",
      "name": "奉贤区",
      "en": "Fengxian",
      "theme": "滨海田园 · 伏羊之乡",
      "styleNote": "草绿 × 泥土棕田园手绘风",
      "blurb": "庄行老街的伏羊节一开，全城飘羊肉香；盛夏的奉贤黄桃，则把海边的阳光都收进了果肉里。",
      "x": 48,
      "y": 68,
      "dishes": [
        {
          "id": "fengxian-zhuanghang-yangrou",
          "name": "庄行羊肉",
          "type": "菜肴",
          "taste": "鲜香细嫩",
          "tasteGroup": "咸鲜",
          "tags": [
            "鲜香",
            "羊肉",
            "非遗"
          ],
          "rating": 4.6,
          "detail": "庄行羊肉烧酒食俗可追溯 600 余年，是上海市级非遗。湖羊以老汤慢火焖煮、不加酱色，白切羊肉皮肉酥嫩、入口即化，配一口烧酒，鲜香暖身。",
          "img": "images/fengxian-zhuanghang-yangrou.jpg",
          "credit": {
            "title": "File:Braised lamb shank with a potato rösti.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Braised_lamb_shank_with_a_potato_r%C3%B6sti.jpg",
            "license": "CC BY-SA 4.0"
          }
        },
        {
          "id": "fengxian-huangtao",
          "name": "奉贤黄桃",
          "type": "蔬果",
          "taste": "清甜多汁",
          "tasteGroup": "清鲜",
          "tags": [
            "清甜",
            "时令",
            "地标"
          ],
          "rating": 4.5,
          "detail": "奉贤特产黄桃，果肉金黄厚实、甜脆多汁，是上海人心中的夏日限定；黄桃罐头与黄桃汽水，更是几代上海小囡的童年味道。",
          "img": "images/fengxian-huangtao.jpg",
          "credit": {
            "title": "File:Australasian peaches in the fruit shop at North Point.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Australasian_peaches_in_the_fruit_shop_at_North_Point.jpg",
            "license": "CC BY-SA 4.0"
          }
        }
      ]
    },
    {
      "id": "chongming",
      "name": "崇明区",
      "en": "Chongming",
      "theme": "生态宝岛 · 江海馈赠",
      "styleNote": "森绿 × 米白自然叶脉风",
      "blurb": "长江口的生态岛，崇明糕、金瓜丝、老毛蟹都是江海与土地的直接馈赠，甜糯与清鲜之间是岛民朴素的生活哲学。",
      "x": 55,
      "y": 8,
      "dishes": [
        {
          "id": "chongming-chongminggao",
          "name": "崇明糕",
          "type": "点心",
          "taste": "甜糯油润",
          "tasteGroup": "甜糯",
          "tags": [
            "甜糯",
            "点心",
            "年味"
          ],
          "rating": 4.7,
          "detail": "崇明人过年必蒸的糯米糕：糯米粉拌入红枣、核桃、蜜饯与猪油，蒸得软糯香甜，切片煎食外脆内糯，是“鱼米之乡”的年味象征。",
          "img": "images/chongming-chongminggao.jpg",
          "credit": {
            "title": "File:Biko (sticky rice cake).jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Biko_(sticky_rice_cake).jpg",
            "license": "CC BY-SA 4.0"
          }
        },
        {
          "id": "chongming-jinguasi",
          "name": "崇明金瓜丝",
          "type": "菜肴",
          "taste": "清鲜爽脆",
          "tasteGroup": "清鲜",
          "tags": [
            "清鲜",
            "时蔬",
            "生态"
          ],
          "rating": 4.6,
          "detail": "崇明金瓜又叫金丝瓜，被誉为“植物海蜇”。瓜瓤自然成丝，焯水后浇葱油凉拌，爽脆鲜甜，是崇明菜桌上最清爽的一道。",
          "img": "images/chongming-jinguasi.jpg",
          "credit": {
            "title": "File:Spaghetti Squash Marinara.jpg",
            "url": "https://commons.wikimedia.org/wiki/File:Spaghetti_Squash_Marinara.jpg",
            "license": "CC BY 2.0"
          }
        }
      ]
    }
  ],
  "links": [
    {
      "id": "xiaolong",
      "name": "小笼之路",
      "emoji": "🥟",
      "desc": "一只小笼的迁徙史：嘉定南翔发源，黄浦豫园扬名，虹口万寿斋守正。",
      "stops": [
        "jiading",
        "huangpu",
        "hongkou"
      ],
      "dishes": [
        "jiading-nanxiang-xiaolong",
        "huangpu-yuyuan-xiaolong",
        "hongkou-wanshouzhai-xiaolong"
      ]
    },
    {
      "id": "yangrou",
      "name": "羊肉江湖",
      "emoji": "🐑",
      "desc": "白切、红烧、伏羊节——真如、张泽、庄行三镇羊肉各成一派。",
      "stops": [
        "putuo",
        "songjiang",
        "fengxian"
      ],
      "dishes": [
        "putuo-zhenru-yangrou",
        "songjiang-zhangze-yangrou",
        "fengxian-zhuanghang-yangrou"
      ]
    },
    {
      "id": "gaotuan",
      "name": "糕团世家",
      "emoji": "🍡",
      "desc": "从徐汇乔家栅到崇明岛，上海人的甜糯基因顺着这条线一路蔓延。",
      "stops": [
        "xuhui",
        "hongkou",
        "minhang",
        "songjiang",
        "jinshan",
        "chongming"
      ],
      "dishes": [
        "xuhui-leishayuan",
        "hongkou-niangaotuan",
        "minhang-qibao-fanggao",
        "songjiang-yexie-ruangao",
        "jinshan-fengjing-zhuangyuangao",
        "chongming-chongminggao"
      ]
    },
    {
      "id": "nongyou",
      "name": "浓油赤酱",
      "emoji": "🍖",
      "desc": "本帮灵魂：从老城厢的排骨年糕出发，途经油爆虾、鮰鱼、丁蹄与扎肉。",
      "stops": [
        "huangpu",
        "changning",
        "baoshan",
        "jinshan",
        "qingpu",
        "pudong"
      ],
      "dishes": [
        "huangpu-paigu-niangao",
        "changning-jinfen-youxia",
        "baoshan-hongshaohuiyu",
        "jinshan-fengjing-dingti",
        "qingpu-zhujiajiao-zharou",
        "pudong-sanlin-kousansi"
      ]
    },
    {
      "id": "shuixiang",
      "name": "水乡之味",
      "emoji": "🛶",
      "desc": "青浦的粽与扎肉、闵行的汤圆、金山的枫泾四宝，都是桥头人家的日常。",
      "stops": [
        "qingpu",
        "minhang",
        "jinshan"
      ],
      "dishes": [
        "qingpu-ajiaozong",
        "qingpu-zhujiajiao-zharou",
        "minhang-qibao-tangyuan",
        "jinshan-fengjing-dingti",
        "jinshan-fengjing-zhuangyuangao"
      ]
    },
    {
      "id": "jianghai",
      "name": "江海馈赠",
      "emoji": "🌊",
      "desc": "长江口的金瓜丝、吴淞口的鮰鱼与鱼圆、杭州湾畔的黄桃，一路向东入海。",
      "stops": [
        "chongming",
        "baoshan",
        "fengxian"
      ],
      "dishes": [
        "chongming-jinguasi",
        "chongming-chongminggao",
        "baoshan-luodian-yuyuan",
        "baoshan-hongshaohuiyu",
        "fengxian-huangtao"
      ]
    }
  ],
  "tasteGroups": [
    {
      "name": "咸鲜",
      "count": 10
    },
    {
      "name": "浓油赤酱",
      "count": 6
    },
    {
      "name": "甜糯",
      "count": 9
    },
    {
      "name": "清鲜",
      "count": 6
    }
  ],
  "stats": {
    "districts": 16,
    "dishes": 31
  }
};
